/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomButtonGroup: typeof import('./../components/bottom-button-group/bottom-button-group.vue')['default']
    Empty: typeof import('./../components/empty/empty.vue')['default']
    Iconfont: typeof import('./../components/iconfont/iconfont.vue')['default']
    ListData: typeof import('./../components/list-data/list-data.vue')['default']
    LoadingView: typeof import('./../components/loading-view/loading-view.vue')['default']
    NavBar: typeof import('./../components/nav-bar/nav-bar.vue')['default']
  }
}
